version: '3.8'
services:
  eureka:
    container_name: eureka
    image: oussamazaoui872/slack-eureka-server:latest
    ports:
      - "8761:8761"
    networks:
      - slack-app
  gateway-chat:
    container_name: gateway-chat
    image: oussamazaoui872/slack-gateway-chat-server:latest
    ports:
      - "8080:8080"
      - "8091:8091"
    networks:
      - slack-app
  messaging-service:
    container_name: messaging-server
    image: oussamazaoui872/slack-messaging-service:latest
    ports:
      - "8082:8082"
      - "8083:8083"
    networks:
      - slack-app
 rabbitmq:
    image: rabbitmq:3.9.11-management-alpine
    container_name: rabbitmq
    ports:
      - "5672:5672"
      - "15672:15672"
    networks:
      - slack-app

networks:
  slack-app:
    driver: bridge

