version: '3.8'
services:
  front:
    image: oussamazaoui872/slack-front:latest
    container_name: front
    ports:
      - "80:80"
  rabbitmq:
    image: rabbitmq:3-management-alpine
    container_name: rabbitmq
    ports:
      - "5672:5672"
      - "15672:15672"
    environment:
      - RABBITMQ_DEFAULT_USER=user
      - RABBITMQ_DEFAULT_PASS=password  
    networks:
      - backend
  eureka:
    container_name: eureka
    image: oussamazaoui872/slack-eureka-server:latest
    ports:
      - "8761:8761"
    networks:
      - backend
  gateway-chat:
    container_name: gateway-chat
    image: oussamazaoui872/slack-gateway-chat-server:latest
    ports:
      - "8091:8080"
    networks:
      - backend
    depends_on:
      - rabbitmq
    environment:
      - MQ_HOST=rabbitmq
      - MQ_USER=user
      - MQ_PASSWORD=password 
      - MQ_PORT=5672
  messaging-service:
    container_name: messaging-service
    image: oussamazaoui872/slack-messaging-service:latest
    ports:
      - "8090:8080"
    networks:
      - backend
      - messaging
    depends_on:
      - rabbitmq
      - database-1
    environment:
      - DB_HOST=database-1
      - DB_NAME=stack-messaging
      - DB_SA_PASSWORD=password@12345#
      - MQ_HOST=rabbitmq
      - MQ_USER=user
      - MQ_PASSWORD=password
      - MQ_PORT=5672
  api-gateway:
    container_name: api-gateway
    image: oussamazaoui872/slack-api-geteway:latest
    ports:
      - "8084:8080"
    networks:
      - backend
    depends_on:
      - eureka
  database-1:
    container_name: database-1
    image: mcr.microsoft.com/mssql/server:2022-latest
    ports:
      - "1433:1433"
    environment:
      - SA_PASSWORD=password@12345#
      - ACCEPT_EULA=Y
    networks:
      - messaging
  notif-service:
    container_name: notif-service
    image: oussamazaoui872/slack-notification-service:latest
    ports:
      - "8090:8080"
    networks:
      - backend
      - notification
    depends_on:
      - database-2
    environment:
      - MQ_HOST=rabbitmq
      - MQ_USER=user
      - MQ_PASSWORD=password
      - MQ_PORT=5672
      - DB_HOST=database-2
      - DB_PORT=27017
      - DB_USER=notif-service
      - DB_PASSWORD=password@12345#
  database-2:
    container_name: database-2
    image: mongo
    restart: always
    ports:
      - "27017:27017"
    environment:
      MONGO_INITDB_ROOT_USERNAME: notif-service
      MONGO_INITDB_ROOT_PASSWORD: password@12345#
    networks:
      - notification
  projectManagement:
    container_name: projectManagement
    image: oussamazaoui872/slack-project-management-service:latest
    ports:
      - "8088:8080":
    depends_on:
      - database-3
    networks:
      - project-management

  database-3:
    image: postgres:latest
    ports:
      - "5432:5432"
    restart: always
    environment:
      POSTGRES_DB: projectManag
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: imad
    networks:
      - project-management

  auth-service:
    container_name: auth-service
    image: oussamazaoui872/slack-auth-service:latest
    depends_on:
      - database-4
    ports:
      - "8089:8080"
    environment:
      - DB_HOST=database-4
      - DB_NAME=auth-stack
      - DB_SA_PASSWORD=password@12345#
      - DB_PORT=1434
    networks:
      - auth-service

  database-4:
    container_name: database-4
    image: mcr.microsoft.com/mssql/server:2022-latest
    ports:
      - "1434:1433"
    environment:
      - SA_PASSWORD=password@12345#
      - ACCEPT_EULA=Y
    networks:
      - auth-service

networks:
  backend:
    driver: bridge
  messaging:
    driver: bridge
  notification:
    driver: bridge
  project-management:
    driver: bridge
  auth-service:
    driver: bridge



