name: CI/CD Pipeline

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build-deploy:
    name: Build test and deploy
    runs-on: ubuntu-latest

    steps:
      - name: checkout code
        uses: actions/checkout@v4

      - name: Setup JDK 17
        uses: actions/setup-java@v4
        with:
          distribution: 'corretto'
          java-version: 17
      - name: Setup Node.js and Angular CLI
        uses: actions/setup-node@v4
        with:
          node-version: '20.x'

      - name: Setup .NET SDK
        uses: actions/setup-dotnet@v3
        with:
          dotnet-version: '7.0.2xx'



      - name: Install dependencies
        run: |
          cd Front
          npm install

      - name: Build the Angular app
        run: |
          cd Front
          npm run build