spring :
    
  datasource:
    url : jdbc:postgresql://database-5:5432/projectManag
    username: postgres
    password: imad
    driver-class-name: org.postgresql.Driver
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        format_sql: true
    database: postgresql
    database-platform: org.hibernate.dialect.PostgreSQLDialect

rabbitmq:
  host: ${MQ_HOST}
  port: ${MQ_PORT}
  username: ${MQ_USER}
  password: ${MQ_PASSWORD}
  queue:
    name: register-pm

  exchange:
    name:
  key :
    name: keySpring
