name: api gateway CI/CD

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

env:
  DOTNET_VERSION: '8.0.x'                   

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    environment: dev
    steps:
      - name: 'Checkout GitHub Action'
        uses: actions/checkout@v3

      - name: Setup DotNet ${{ env.DOTNET_VERSION }} Environment
        uses: actions/setup-dotnet@v3
        with:
          dotnet-version: ${{ env.DOTNET_VERSION }}

      - name: Restore dependencies
        run: |
         cd api-gateway
         dotnet restore

      - name: Build project
        run: |
         cd api-gateway
         dotnet build

      #- name: Test project
       # run: dotnet test
        
      - name: Get current date
        id: date
        run: echo "::set-output name=date::$(date +'%Y-%m-%d-%H-%M-%S')"
          
      - name: Build Docker image
        uses: docker/build-push-action@v5
        with:
           context: ./api-gateway
           dockerfile: Dockerfile
           push: false
           tags: ${{ secrets.DOCKER_HUB_USERNAME }}/slack-api-geteway:latest
           
           
      - name: login to docker hub
        uses: docker/login-action@v3
        with:
           username: ${{ secrets.DOCKER_HUB_USERNAME }}
           password: ${{ secrets.DOCKER_HUB_ACCESS_TOKEN }}

      - name: push image
        uses: docker/build-push-action@v5
        with:
           context: ./api-gateway
           dockerfile: Dockerfile
           push: true
           tags: ${{ secrets.DOCKER_HUB_USERNAME }}/slack-api-geteway:latest
