name: Front CI/CD

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build-deploy:
    name: Build test and deploy
    runs-on: ubuntu-latest
    steps:
      - name: checkout code
        uses: actions/checkout@v4

      - name: Setup Node.js and Angular CLI
        uses: actions/setup-node@v4
        with:
          node-version: '20.x'
      - name: Install dependencies
        run: |
          cd Front
          npm install
      
      - name: Build the Angular app
        run: |
          cd Front
          npm run build
          
      - name: Get current date
        id: date
        run: echo "::set-output name=date::$(date +'%Y-%m-%d-%H-%M-%S')"
          
      - name: Build Docker image
        uses: docker/build-push-action@v5
        with:
           context: ./Front
           dockerfile: Dockerfile
           push: false
           tags: ${{ secrets.DOCKER_HUB_USERNAME }}/slack-front:latest
           
           
      - name: login to docker hub
        uses: docker/login-action@v3
        with:
           username: ${{ secrets.DOCKER_HUB_USERNAME }}
           password: ${{ secrets.DOCKER_HUB_ACCESS_TOKEN }}

      - name: push image
        uses: docker/build-push-action@v5
        with:
           context: ./Front
           dockerfile: Dockerfile
           push: true
           tags: ${{ secrets.DOCKER_HUB_USERNAME }}/slack-front:latest
