name: notif Service CI/CD

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

env:
  DOTNET_VERSION: '8.0.x'

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    environment: dev
    steps:
      - name: 'Checkout GitHub Action'
        uses: actions/checkout@v3

      - name: Setup DotNet ${{ env.DOTNET_VERSION }} Environment
        uses: actions/setup-dotnet@v3
        with:
          dotnet-version: ${{ env.DOTNET_VERSION }}

      - name: Restore dependencies
        run: |
          cd notif-service
          dotnet restore notif-service.sln

      - name: Build project
        run: |
          cd notif-service
          dotnet build notif-service.sln

      - name: Test project
        run: |
         cd notif-service
         dotnet test

      - name: Build Docker image
        uses: docker/build-push-action@v5
        with:
          context: ./notif-service
          dockerfile: Dockerfile
          push: false
          tags: ${{ secrets.DOCKER_HUB_USERNAME }}/slack-notification-service:latest


      - name: login to docker hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKER_HUB_USERNAME }}
          password: ${{ secrets.DOCKER_HUB_ACCESS_TOKEN }}

      - name: push image
        uses: docker/build-push-action@v5
        with:
          context: ./notif-service
          dockerfile: Dockerfile
          push: true
          tags: ${{ secrets.DOCKER_HUB_USERNAME }}/slack-notification-service:latest
